### GraphQL repository query
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "query { find(createdFrom: \"2024-01-01\", language: \"Java\") { name createdAt owner { url login } score pushedAt forksCount } }"
}

