spring:
  application:
    name: ${SERVICE_NAME:@project.name@}
    version: @project.version@
  web:
    resources:
      add-mappings: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_batch_fetch_size: 30
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/repo_discovery}
    username: ${DATASOURCE_USER:postgres}
    password: ${DATASOURCE_PASSWORD:password}
logging:
  index: ${LOGGING_INDEX_PREFIX:live-data}
  config: classpath:logback-${LOGGING_CONFIG_SUFFIX:development}.xml