spring:
  application:
    name: ${SERVICE_NAME:@project.name@}
    version: @project.version@
  web:
    resources:
      add-mappings: false
logging:
  config: classpath:logback-${LOGGING_CONFIG_SUFFIX:development}.xml

github:
  base-url: https://api.github.com/
  connect-timeout: 5s
  read-timeout: 3s
  default-fetch-count: 100

