spring:
  application:
    name: ${SERVICE_NAME:@project.name@}
    version: @project.version@
  web:
    resources:
      add-mappings: false
logging:
  config: classpath:logback-${LOGGING_CONFIG_SUFFIX:development}.xml

github:
  base-url: https://api.github.com/
  connect-timeout: 5s
  read-timeout: 3s
  default-fetch-count: 100

rule:
  configs:
    dynamic-rule-properties:
      forks-top-weight: "3"
      forks-mid-weight: "2"
      forks-bot-weight: "1"

      star-top-weight: "5"
      star-mid-weight: "3"
