spring:
  application:
    name: ${SERVICE_NAME:@project.name@}
    version: @project.version@
  web:
    resources:
      add-mappings: false
logging:
  index: ${LOGGING_INDEX_PREFIX:live-data}
  config: classpath:logback-${LOGGING_CONFIG_SUFFIX:development}.xml