name: Maven Compile on Change

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compile with Maven
        run: mvn clean compile
